// The Codex: the canon of the world, written once, with the living world's numbers woven in.
import { BLOODS, SPARTOI_HOUSES, DISTRICTS, OFFICES, BEAM, ST } from "./sim/lore.js";
import { MONTHS, dateOf } from "./sim/culture.js";
import { CITIES } from "./sim/war.js";
import { CRAFTS } from "./sim/drift.js";
import { myths } from "./sim/rumor.js";
import { cityForm, catalogue } from "./sim/poetics.js";

const D_AGORA_SKIP = -1;
const BLOOD_LORE = {
  spartoi: ["Apollodorus 3.4.1; Apollonius 3.1354ff", "Dragon's teeth sown in the Field of Ares. Jason threw a stone among the first crop and they killed each other until five were left: Echion, Udaeus, Chthonius, Hyperenor, Pelorus. Their houses still quarrel.", "The many. Farmers, rowers, soldiers: fashionable, quarrelsome, the backbone of every vote."],
  gegeneis: ["Apollonius 1.936-1011", "Six-armed Earthborn of Bear Mountain, cut down at Chytus harbour and stacked on the shore like timber. The city is built from their bodies.", "Old, stubborn, quarrymen and wall-builders, keepers of death-cloaks and the Reapers' trade."],
  argyreoi: ["Hesiod, Works and Days 127-142", "Hesiod's Silver Race: a hundred years of childhood, then a short, foolish adulthood of insult and impiety. After death they became the blessed spirits under the earth.", "Pampered gentry of Iolcus with long memories and short tempers."],
  gorgonides: ["Ovid, Metamorphoses 4.740-752", "When Perseus set Medusa's severed head on seaweed, the weed drank her poison and hardened into coral. Alive below the water, stone above it.", "Divers and reef-builders who go bare-headed and mistrust the land."],
  anthemoessans: ["Apollonius 3.844-868, 4.892; Odyssey 12.45", "From the Sirens' flowery isle, where the meadow is a heap of bones, and from the Prometheion, the flower that grew from the Titan's dripping ichor and screams when cut.", "Gardeners, herbalists and the Siren-haunted; their medicine is made from suffering."],
  lithinoi: ["Apollodorus 1.7.2; Pindar, Olympian 9.43-46", "After the flood Deucalion and Pyrrha threw stones over their shoulders, and the stones became a people: laas, stone; laos, people.", "Few, patient, aristocratic; in the art they never move. They keep the law of the flood."],
  chryseoi: ["Hesiod, Works and Days 109-126", "The Golden Race lived without toil and died as if falling asleep. Afterwards they became spirits clothed in mist, who watch judgements and cruel deeds and give wealth.", "The richest blood: watchers on the Mist-terraces, judges and lenders."],
  phaethontes: ["Apollonius 4.596-626, 4.727ff", "Phaethon fell burning into the Eridanus, and the lake still smoulders; birds that fly over it plunge into the flame. Helios' line, whose eyes shoot a golden gleam.", "Twenty-five, feared, glowing; alchemists of the forbidden lake."],
  ouranidai: ["Apollonius 4.990; Odyssey 8.555", "Of the blood of Uranus, like the Phaeacians whose ships steer themselves and know men's thoughts.", "Nine strangers on Drepane: serene, prophetic, unreadable."],
};
const PLACE_LORE = {
  agora: "The launch harbour where the Argo was first pushed into the sea; now the market and the seat of the Boule.", ares: "Where the dragon's teeth were sown. The largest city, and the hungriest.",
  bear: "Arkton Oros, home of the six-armed Earthborn; mines, snow and grudges.", anthemoessa: "The Sirens' isle. Flowers grow from the dead here; DO NOT LISTEN.",
  reef: "Coral born of the Gorgon's blood, and the Gorgonides who dive it.", eridanus: "Phaethon's lake, still burning. An exclusion zone of glowing people.",
  drepane: "The Sickle, far island of the self-steering ships.", mist: "Terraces wrapped in Hesiod's mist, where the Golden Race keeps watch.",
  strand: "Where Deucalion threw the stones that became people.", iolcus: "Pelias' city, where the voyage began with one sandal; now the Silver Race's halls.",
  grove: "The Grove of Ares, where the Fleece once hung and THE DRAGON SLEEPS.", lemnos: "Hephaestus' smoking island, where the women once murdered their men in a night and told visitors they had gone away.",
  forges: "The Chalybes, most wretched of men, who work iron in the dark.", pyra: "The pyre on the headland. Burned tokens lie here five real days, while their art still shows fire; mortal Leaves burn for three.",
  asphodel: "The Asphodel Meadow. Graves with oars planted on them, the unmade among them, and broken Argonauts waiting for their bones to knit.",
};

export function renderCodex(w, seed, view, esc, dayLabel, linkify) {
  const A = w.A, alive = (i) => A.status[i] === ST.living, bloodCount = BLOODS.map(() => 0); let leaves = 0, graves = 0, unmade = 0;
  for (let i = 0; i < w.N; i++) { if (alive(i)) { if (i < 9999) bloodCount[A.bones[i]]++; else leaves++; } if (A.status[i] === ST.asphodel) { graves++; if (i < 9999) unmade++; } }
  const deeds = (w.maker || {}), S = [];
  S.push(`<h3>I. The voyage</h3>
  <p>Before the world there was the <b>Maker</b>, whom the chain knows as alphacentaurikid and the visors call ACK. On the twenty-sixth day of the month the chain calls August, the Maker sowed ten thousand dragon's teeth, and out of the furrows came the <b>Minyai</b>: skeletons, already past death, each with its own bones, cloak, crown and sight. That was <b>the Sowing</b>, and everything that happened between it and the first day of the Reckoning is remembered as prehistory.</p>
  <p>The Minyai are bone. Wounds, plague and hunger only <i>break</i> them; their pieces are carried to the Asphodel Meadow and knit again. <b>Only fire unmakes them</b>, and fire comes only from the chain: when a holder sends an Argonaut to the dead address, it burns on the Pyra for as long as its art shows flame and is then buried with an oar on its mound. So far ${unmade} have been unmade.</p>
  <p>The Minyai cannot age, but they can love, and lovers sow children. The children are <b>the Leaves</b>, after Homer: <i>"As is the generation of leaves, so is that of men"</i> (Iliad 6.146). Leaves are born, grow old within days and truly die. ${leaves.toLocaleString()} live now; ${graves - unmade} lie in the meadow.</p>
  <p>Above it all hangs the <b>Argo</b>, whose prow holds a beam cut from Dodona's oak that speaks with a human voice. When the Maker changes the renderer, the beam speaks one of the visor phrases (${BEAM.slice(0, 8).join(", ")} …) and the whole city's mind turns. And somewhere in the Grove of Ares there is still one <b>Golden Fleece</b>, worn by a single Argonaut: the prize every faction covets.</p>
  <p>Nothing in the world is steered. The chain is <b>Moira</b>, fate: sales move an Argonaut to a new house and bring gold from Colchis, swaps exchange hostages under the law of xenia, rulings of the Maker remake a character, burns light the Pyra. Everything else the Minyai do themselves.</p>`);
  S.push(`<h3>II. The bloods</h3><p class="muted">Each Argonaut belongs to a blood by its Bones trait. The Sown are divided further into the five houses of the first sowing.</p>` +
    BLOODS.map((B, k) => { const L = BLOOD_LORE[B.key]; return `<div class="law"><b style="color:${B.color}">${esc(B.name)}</b>, ${esc(B.title)} <span class="num">${B.bones} bones · ${bloodCount[k].toLocaleString()} living</span><p>${esc(L[1])}</p><p class="muted">${esc(L[2])} <i>Source: ${esc(L[0])}.</i></p></div>`; }).join("") +
    `<p class="muted">The five houses of the Sown: ${SPARTOI_HOUSES.map((h) => `${esc(h.name)} (${esc(h.title)})`).join(", ")}.</p>`);
  S.push(`<h3>III. The places</h3>` + DISTRICTS.map((d, k) => {
    const c = CITIES.includes(k) && w.war ? w.war : null, dm = c ? c.dom[k] : null;
    const crafts = w.crafts ? CRAFTS.map((cr, ci) => ({ n: cr.name, v: w.crafts[k][ci] })).filter((x) => x.v >= 70).map((x) => x.n) : [];
    return `<div class="law"><b>${esc(d.name)}</b>${c && c.lord[k] !== k ? ` <span class="num">vassal of ${esc(DISTRICTS[c.lord[k]].name)}</span>` : ""}<p>${esc(PLACE_LORE[d.key] || "")}</p>${dm ? `<p class="muted">${dm.pop} adults · ${esc(w.factions[dm.faction] ? w.factions[dm.faction].name : "")} · ${esc(w.faiths[dm.faith] ? w.faiths[dm.faith].name : "")}${crafts.length ? " · masters of " + esc(crafts.join(", ")) : ""} · cohesion ${Math.round(c.S[k] * 100)}</p>` : ""}</div>`; }).join(""));
  S.push(`<h3>IV. The powers and offices</h3>
  <p><b>The Maker</b> acts only through the chain: setTraits remakes a character (it has touched #8393 and #7920), setRenderer makes the Argo speak, new contracts become new stars, and the DeadClock's notice tolls over Asphodel. On the fifth day of October the Maker built a barrel of oil for #8985 alone, thirty-five minutes after its holder burned it.</p>
  <p><b>Charon</b> takes two obols from every funeral, which is how money leaves the world. <b>The Reapers</b> (the Death-cloaked) carry the broken to Asphodel, bury the dead and keep the watch when the Boule pays them.</p>
  <p><b>Offices</b> are named for the crew of the Argo: ${OFFICES.map((o) => `${esc(o.title)}, ${esc(o.role)}`).join("; ")}.</p>`);
  S.push(`<h3>V. The calendar</h3><p>${MONTHS.map((m, k) => `${k + 1}. ${m}`).join(" · ")}. Each month is thirty days and the year 360: one sim day for every real hour, so a year passes in fifteen real days. The Pagasaia opens the year; on 11 Anthesterion the dead walk the city for three days; the Games of Kolchis close the harvest. Any memory still strong after a year becomes a festival of its own.</p>`);
  // the ages: thirty-day eras named by their most salient story
  const st = (w.storyLog || []), eras = [];
  for (let d0 = -360; d0 < w.day; d0 += 30) { const win = st.filter((x) => x.day >= d0 && x.day < d0 + 30).sort((a, b) => b.score - a.score)[0]; if (win) eras.push({ d0, title: win.era || ("the Age of " + win.title), text: win.text }); }
  S.push(`<h3>VI. The ages</h3>${eras.length ? eras.map((e) => `<div class="law"><b>${esc(e.title.charAt(0).toUpperCase() + e.title.slice(1))}</b><span class="num">${dayLabel(e.d0)}</span><p>${linkify(e.text)}</p></div>`).join("") : '<p class="muted">The ages are named from the front page; open it once and return.</p>'}`);
  // dynasties
  const lines = {}; for (let i = 9999; i < w.N; i++) { const L = A.lineage[i]; const o = lines[L] || (lines[L] = { n: 0, alive: 0, gen: 0 }); o.n++; if (alive(i)) o.alive++; o.gen = Math.max(o.gen, A.gen[i]); }
  const top = Object.entries(lines).sort((a, b) => b[1].alive - a[1].alive || b[1].n - a[1].n).slice(0, 12);
  S.push(`<h3>VII. Dynasties</h3><p class="muted">Lines are named for the Argonaut who sowed them; the founders never age, so the oldest houses are watched over by their own beginning.</p>${top.map(([L, o]) => `<div class="law"><a class="who" data-i="${L}">${esc(view.name(Number(L)))}</a><span class="num">${o.alive} living of ${o.n} ever born · ${o.gen} generations</span></div>`).join("") || '<p class="muted">No lines yet.</p>'}`);
  // faiths and their accounts of the great memories
  const mem = (w.memory || []).filter((m) => ["burn", "war", "lemnian", "prophet", "riot", "revolt", "schism", "temple", "beast", "hunt", "stone", "colony"].includes(m.kind)).slice(-8).reverse();
  S.push(`<h3>VIII. How the faiths tell it</h3>${mem.map((m) => `<div class="law"><b>${esc(m.name.charAt(0).toUpperCase() + m.name.slice(1))}</b><span class="num">${dayLabel(m.day)}</span>${myths(w, m, view.name).map((x) => `<p><span style="color:${x.color}">${esc(x.faith)}:</span> ${linkify(x.text)}</p>`).join("")}</div>`).join("") || '<p class="muted">No great memories yet.</p>'}`);
  S.push(`<h3>IX. Relics</h3><p class="muted">Things that remember every hand they passed through: spears raised over victories, the first teeth of new gods, the cradle-teeth of each new generation, the shears that cut the Fleece.</p>${(w.relics || []).slice().reverse().slice(0, 30).map((r) => `<div class="law"><b>${esc(r.name.charAt(0).toUpperCase() + r.name.slice(1))}</b><span class="num">made ${dayLabel(r.born)} · ${r.history.length} hands</span><p>${r.history.map(([d, h, how]) => `<a class="who" data-i="${h}">${esc(view.name(h).split(" ").slice(0, 2).join(" "))}</a> (${esc(how)})`).join(" → ")}</p></div>`).join("") || '<p class="muted">None yet.</p>'}`);
  // the laws of the world: how the newer systems work, with their living numbers
  const law = (t, src, body) => `<div class="law"><b>${t}</b><span class="num">${src}</span><p>${body}</p></div>`;
  const nAlive = (f) => { let n = 0; for (let i = 0; i < w.N; i++) if (alive(i) && f(i)) n++; return n; };
  const beasts = (w.beasts || []).map((b) => `${esc(b.name)} (${b.alive ? `hunger ${b.hunger}, ${b.kills} taken` : `slain${b.slainBy >= 0 ? ` by <a class="who" data-i="${b.slainBy}">${esc(view.name(b.slainBy))}</a>` : ""}`})`).join("; ");
  const houses = Object.entries(w.houses || {}).sort((a, b) => b[1].r - a[1].r).slice(0, 6).map(([L, h]) => `<a class="who" data-i="${L}">${esc(view.name(Number(L)))}</a> ${h.r}${h.legacies.length ? ` (${h.legacies.join(", ")})` : ""}`).join("; ");
  const iron = w.iron ? ["shame and justice still walk the earth", "Aidos has left the earth", "Nemesis has left the earth", "the Leaves are born grey at the temples"][w.iron.tier] : "";
  S.push(`<h3>X. The laws of the world</h3><p class="muted">What the engine does each day, beyond the market and the Boule. Every rule is drawn from a source.</p>` +
    law("Miasma and the Erinyes", "Parker, Miasma; Aeschylus, Eumenides", `Blood stains the killer; a city full of unwashed killers sickens. Kin-slayers are hounded by the Furies until a priest washes them in a piglet's blood. Now: ${nAlive((i) => A.miasma[i] > 0)} stained, ${nAlive((i) => A.fury[i] > 0)} hounded.`) +
    law("Blood-price and the feud", "Iliad 9.632, 18.497; Draco", `After a killing the dead one's people choose: blood-price (a Leaf's life 120 obols, broken bone half, because bone knits) or vengeance. A killer may clasp the avenger's knees. Open feuds: ${Object.keys(w.feuds || {}).length}; sworn avengers: ${nAlive((i) => A.avenge[i] > 0)}.`) +
    law("The Areopagus", "Talk of the Town; Aeschylus", `Some killings are seen by nobody. Belief gathers on suspects, true or not, and twelve jurors decide; a tie acquits. Open cases: ${(w.cases || []).filter((c) => c.open).length}.`) +
    law("Liturgies and antidosis", "Athenian law; Lysias 21", `Each month the very rich are named to buy grain for the hungry, pay a convoy's rowers or a chorus. A man named may challenge a richer one: take the duty, or swap estates.`) +
    law("Xenia", "Iliad 6.119-236", `Every sale on the chain binds the old house and the new as guest-friends. They send gifts, lower their spears in battle, and killing one is the worst stain there is. Bonds: ${Object.keys(w.xenia || {}).length}.`) +
    law("Lethe and Memory", "the Orphic gold tablets; Apollonius 1.915", `A broken Argonaut who re-knits drinks from the white cypress spring and forgets: bonds, memories, sometimes its beloved. Initiates of the Kabeiroi, and those the Maker's ruling has touched, drink from the lake of Memory. Initiates: ${nAlive((i) => A.mystes[i] > 0)}.`) +
    law("Oaths and curses", "Herodotus 6.86; the Cyrene oath", `Broken oaths curse a line for three generations. Cursed lines: ${Object.keys(w.curses || {}).length}.`) +
    law("Oracles", "Herodotus 1.53; the Dodona tablets", `The Pythia answers twice a month in verse that the world fulfils after the fact; when the Argo's beam speaks, the city asks the oak. Pending prophecies: ${(w.prophecies || []).length}.`) +
    law("Beasts and hunts", "Apollodorus 1.8; Koster on Ultima Online", `${beasts.charAt(0).toUpperCase() + beasts.slice(1)}.`) +
    law("Great houses", "CK3 renown", houses || "No house has yet made a name.") +
    law("The stone and the Iron clock", "Apollonius 3.1354; Works and Days 174-201", `When the five houses of the Sown are at each other's throats, or a token of the Sown is sold for a pittance, a stone falls among them. The Iron clock counts Hesiod's signs: ${iron} (index ${w.iron ? w.iron.index : 0}).`) +
    law("Weather and colonies", "Works and Days; Herodotus 4.150", `Dry districts: ${DISTRICTS.filter((d, k) => w.dry && w.dry[k] >= 20).map((d) => d.name).join(", ") || "none"}. Colonies sent by lot: ${(w.colonies || []).length}.`) +
    law("The political stress index", "Turchin, Secular Cycles", `${w.psi ? `${w.psi.phase} (${w.psi.v})` : ""}: too many would-be great, too few places, hungry streets.`) +
    law("Songs, hooks and movements", "Dwarf Fortress; CK3; Victoria 3", `The Orpheus sings the city's heaviest memory each week, and sung things last; blame-songs cost office-holders their name. Blackmail moves votes in the Boule. When the age is hard, the would-be great lead the hungry: petition, agitation, a rising. Movements now: ${(w.movements || []).length}.`) +
    law("Horrors and wonders", "Apollonius; Pausanias; Philostratus", `The Kēres after lost battles, the Empusa lover, Lamia in famine, the dead the Pyra refuses, Trophonius' cave, Cleomedes and the statue of Theagenes, the Cattle of the Sun, the Hero of Temesa${(w.temesa || []).length ? ` (${(w.temesa || []).length} heroes take tribute now)` : ""}.`) +
    law("The voyage", "Apollonius 2, 4; Odyssey 21", `${w.rocks && w.rocks.open ? "The Clashing Rocks stand still for ever." : "The Clashing Rocks still shut the lane from the Reef to Drepane."} ${w.talos && w.talos.alive ? "Talos walks the harbour." : "Talos has fallen."} Ships sail past the edge of the map to Colchis, Crete, the Hyperboreans and the Isles of the Blest${(w.voyages || []).length ? `; ${(w.voyages || []).length} at sea now` : ""}.`) +
    law("Households and crafts", "Hesiod; Henrich; Solon", `Skill is learned at work and passed to apprentices; orphans find guardians; households share a common jar; neighbours lend grain to be repaid with the same measure or better; when debts pile up, the Boule may cancel them all.`) +
    law("Plague and quarantine", "Thucydides 2.47-54", `The recovered are not taken twice for a season. A district with too many sick is closed. Closed now: ${DISTRICTS.filter((d, k) => w.quarantine && w.quarantine[k] >= w.day).map((d) => d.name).join(", ") || "none"}.`) +
    law("The sea's yield", "the tragedy of the commons", `Fish stocks: ${w.fish ? DISTRICTS.map((d, k) => [d, w.fish[k]]).filter(([d, f]) => f < 1000 && ["fish"].includes(d.res) || f < 700).map(([d, f]) => `${d.name.replace(/^the /, "")} ${Math.round(f / 10)}%`).join(", ") || "all full" : ""}.`) +
    law("What cannot be undone", "Kenshi's world states", Object.keys(w.vacant || {}).length ? `Empty for ever, their holders burned on the chain: ${Object.keys(w.vacant).map((k) => (OFFICES.find((o) => o.key === k) || {}).title || k).join(", ")}.` : "Nothing yet. When the chain burns an office-holder, that office will stay empty for ever.") +
    ((w.games && w.games.champions || []).length ? law("Champions of the games", "Iliad 23", w.games.champions.slice(0, 6).map(([d, i, nm]) => `<a class="who" data-i="${i}">${esc(view.name(i))}</a>, ${esc(nm)} (${dayLabel(d)})`).join("; ")) : ""));
  { const cat = catalogue((w.storyLog || []).filter((x) => x.day > w.day - 31), (i) => view.name(i).split(" ")[0]); if (cat.length) S.push(`<h3>The month in song</h3><blockquote class="poem">${cat.map((l) => `<span>${esc(l)}</span>`).join("")}<cite>the Orpheus, a catalogue in the manner of the Ships</cite></blockquote>`); }
  S.push(`<h3>XI. Songs of the cities</h3><p class="muted">Every city sings in its own manner; the Orpheus sings the front page each day in the manner of their own city.</p>${CITIES.filter((k) => k !== D_AGORA_SKIP).map((k) => { const f = cityForm(k); return `<div class="law"><b>${esc(DISTRICTS[k].name.replace(/^./, (c) => c.toUpperCase()))}</b><span class="num">${esc(f.name)}, ${esc(f.measure)}</span><p><i>${esc(f.refrain)}</i></p></div>`; }).join("")}`);
  S.push(`<h3>XII. The chain beneath</h3><p>The world is computed from the real Argonauts collection (contract 0x387c…392c) by a deterministic engine: every Argonaut's traits, every transfer since the Sowing (replayed as prehistory), and every new block since. Twenty-two tokens had been burned by the sixth of October, twenty-one of them by one wallet in two days of September; #8985 burned on the fifth of October. The art has changed eight times, rulings have touched two tokens, and the visors carry forty-one phrases from the Argonautica and the Maker's own world.</p>`);
  return S.join("");
}
